#!/bin/sh
brew install aacgain
brew install ansible-lint
brew install autoconf
brew install automake
brew install awscli
brew install bash-completion
brew install bison
brew install bzip2
brew install curl
brew install nodebrew
brew install direnv
brew install fasd
brew install fish
brew install freetype
brew install gdbm
brew install gettext
brew install ghq
brew install git
brew install gmp
brew install goenv
brew install graphviz
brew install httpie
brew install hub
brew install icu4c
brew install ipcalc
brew install jpeg
brew install jq
brew install libevent
brew install libpng
brew install libtool
brew install libxml2
brew install libyaml
brew install mackup
brew install mas
brew install mcrypt
brew install mhash
brew install nodebrew
brew install oniguruma
brew install openssl
brew install pcre
brew install pcre2
brew install peco
brew install php70
brew install phpbrew
brew install pkg-config
brew install qcachegrind
brew install qt
brew install rbenv
brew install re2c
brew install readline
brew install ruby-build
brew install source-highlight
brew install the_silver_searcher
brew install telnet
brew install tig
brew install tree
brew install unixodbc
brew install vagrant-completion
brew install vim
brew install wget
brew install watch
brew install xz
brew install zlib
brew install zsh
brew install zsh-completions
brew install zsh-syntax-highlighting
