#!/bin/sh
brew cask instal alfred
brew cask instal appcleaner
brew cask instal atom
brew cask instal chatwork
brew cask instal chromium
brew cask instal clipy
brew cask instal coteditor
brew cask instal dash
brew cask instal datagrip
brew cask instal docker
brew cask instal dropbox
brew cask instal evernote
brew cask instal firefox
brew cask instal flash
brew cask instal flash-player
brew cask instal flux
brew cask instal franz
brew cask instal github-desktop
brew cask instal google-drive-file-stream
brew cask instal google-chrome
brew cask instal google-chrome-canary
brew cask instal google-japanese-ime
brew cask instal intellij-idea
brew cask instal iterm2
brew cask instal java6
brew cask instal jetbrains-toolbox
brew cask instal karabiner-elements
brew cask instal keepassx
brew cask instal magican
brew cask instal mysqlworkbench
brew cask instal p4merge
brew cask instal phpstorm
brew cask instal postman
brew cask instal rdm
brew cask instal sequel-pro
brew cask instal slack
brew cask instal shiftit
brew cask instal sourcetree
brew cask instal sublime-text
brew cask instal tableplu
brew cask instal the-unarchiver
brew cask instal vagrant
brew cask instal virtualbox
brew cask instal visual-studio-code
brew cask instal vivaldi
brew cask instal vlc
